#!/bin/bash

while read pkgline; do
    pkg="${pkgline%% *}"
    pkg_ver="${pkgline##* }"

    while read line; do
        # "black list"
        [ "${line:2:1}" = '5' ] || continue

        [ "${skip_config_files:-true}" = 'true' ] && [ "${line:10:1}" = 'c' ] && continue

        echo "${line:12}" | grep -qE '^(/etc/|/root/)' && continue

        echo -e "${pkg}\t${pkg_ver}\t${line}"
    done < <(nice -n 19 ionice -c 3 dpkg --verify "$pkg")
done < <(dpkg-query -W -f='${Package} ${Version}\n')

