# fuel_user: 'admin'
# fuel_pass: 'admin'
# fuel_ip: '127.0.0.1'
rqdir: './rq'
rqfile: './rq.yaml'
cudet_db_dir: './db'
outdir: '/tmp/cudet/info'
hard_filter:
    no_roles: ['fuel']
    status: ['ready']
    online: True
    # you can filter by roles
    roles: []
    # you can filter by node ids
    id: []
    # you can filter by env ids
    cluster: []
# timeout is seconds for data collection (per command) - increase if needed
timeout: 600
clean: False
